apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc-microservice.name" . }}
  labels:
{{ include "cc-microservice.service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cc-microservice.name" . }}