{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cc-microservice.name" . }}
  labels:
    release: {{ .Values.prometheus.release }}
spec:
  endpoints:
  - path: {{ .Values.service.metrics }}
  namespaceSelector:
    matchNames:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cc-microservice.name" . }}
{{ end -}}